FROM python:3.8-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    software-properties-common \
    git \
    tesseract-ocr libgl1 \
    && rm -rf /var/lib/apt/lists/*

# Copy the current directory contents into the container at $HOME/app setting the owner to the user
COPY ./requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt

RUN pip install "unstructured[all-docs]"

# RUN --mount=type=secret,id=OPENAI_API_KEY,mode=0444,required=true \
#    cat /run/secrets/openai_api_key > app_llmchat.py

# Set up a new user named "user" with user ID 1000
RUN useradd -m -u 1000 user

# Switch to the "user" user
USER user

# Set home to the user's home directory
ENV HOME=/home/user \
    PATH=/home/user/.local/bin:$PATH

# Set the working directory to the user's home directory
WORKDIR $HOME/app

COPY --chown=user . $HOME/app

EXPOSE 7860

# HEALTHCHECK CMD curl --fail http://localhost:7860/_stcore/health

ENTRYPOINT ["streamlit", "run", "app_llmchat.py", "--server.port=7860", "--server.address=0.0.0.0"]