name: Python application with Github Actions

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8" # | operator error E1131 in rag chain https://github.com/pylint-dev/pylint/issues/7381 use python 3.10 to bypass this
      
      - name: Install dependencies
        run: |
          make  install
      
      - name: Install requirements
        run: |
          make init
    
      - name: Format code
        run: |
          make format

      - name: Lint with pyLint
        run: |
          make lint